version: '3.3'

services:

  mysql:
      image: mysql:8.0.19
      container_name: mysql
      command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
      environment:
        MYSQL_DATABASE: curso_mysql
        MYSQL_ROOT_PASSWORD : curso
      volumes:
        - ~/Documents/curso_mysql:/var/lib/mysql