-- MySQL Script generated by MySQL Workbench
-- vie 19 feb 2021 20:24:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_jugador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nacionalidad` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ju_na`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ju_na` (
  `ju_id_jugador` INT NOT NULL,
  `na_id_nacionalidad` INT NOT NULL,
  PRIMARY KEY (`ju_id_jugador`, `na_id_nacionalidad`),
  INDEX `fk_jugador_has_nacionalidad_nacionalidad1_idx` (`na_id_nacionalidad` ASC) VISIBLE,
  INDEX `fk_jugador_has_nacionalidad_jugador_idx` (`ju_id_jugador` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_has_nacionalidad_jugador`
    FOREIGN KEY (`ju_id_jugador`)
    REFERENCES `mydb`.`jugador` (`id_jugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_has_nacionalidad_nacionalidad1`
    FOREIGN KEY (`na_id_nacionalidad`)
    REFERENCES `mydb`.`nacionalidad` (`id_nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
