-- MySQL Script generated by MySQL Workbench
-- vie 12 feb 2021 19:49:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nacionalidad` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `detalle_nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `detalle_equipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posicion` (
  `id_posicion` INT NOT NULL AUTO_INCREMENT,
  `detalle_posicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_posicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  `posicion_id_posicion` INT NOT NULL,
  `nacionalidad_id_nacionalidad` INT NOT NULL,
  PRIMARY KEY (`id_jugador`, `equipo_id_equipo`, `posicion_id_posicion`, `nacionalidad_id_nacionalidad`),
  INDEX `fk_jugador_equipo_idx` (`equipo_id_equipo` ASC) VISIBLE,
  INDEX `fk_jugador_posicion1_idx` (`posicion_id_posicion` ASC) VISIBLE,
  INDEX `fk_jugador_nacionalidad1_idx` (`nacionalidad_id_nacionalidad` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_equipo`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `mydb`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_posicion1`
    FOREIGN KEY (`posicion_id_posicion`)
    REFERENCES `mydb`.`posicion` (`id_posicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_nacionalidad1`
    FOREIGN KEY (`nacionalidad_id_nacionalidad`)
    REFERENCES `mydb`.`nacionalidad` (`id_nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
